In [1]:
#Importing important libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#Reading the dataset
df = pd.read_excel("data_final.xlsx")

In [3]:
#Checking first five values of the dataset
df.head()

observation  feature   price
0         0.44     0.68  511.14
1         0.99     0.23  717.10
2         0.84     0.29  607.91
3         0.28     0.45  270.40
4         0.07     0.83  289.88

In [4]:
#Checkmg for the null values
df.isnull().sum()

observation    0
feature        0
price          0
dtype: int64

In [54]:
#Observation:
# TherE are 0 Null values in each Columns

In [5]:
df.duplicated().sum()
#Observation: There are 0 duplication in the columns

0

In [6]:
df.info()
#Getting information about the data
#The dataset has 100 rows with no null values and 3 rows

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   observation  100 non-null    float64
 1   feature      100 non-null    float64
 2   price        100 non-null    float64
dtypes: float64(3)
memory usage: 2.5 KB


In [7]:
#Separating dependent and independent data in separate variables
X = df.iloc[:, :-1].values
y = df['price'].values

In [8]:
X

array([[0.44, 0.68],
       [0.99, 0.23],
       [0.84, 0.29],
       [0.28, 0.45],
       [0.07, 0.83],
       [0.66, 0.8 ],
       [0.73, 0.92],
       [0.57, 0.43],
       [0.43, 0.89],
       [0.27, 0.95],
       [0.43, 0.06],
       [0.87, 0.91],
       [0.78, 0.69],
       [0.9 , 0.94],
       [0.41, 0.06],
       [0.52, 0.17],
       [0.47, 0.66],
       [0.65, 0.43],
       [0.85, 0.64],
       [0.93, 0.44],
       [0.41, 0.93],
       [0.36, 0.43],
       [0.78, 0.85],
       [0.69, 0.07],
       [0.04, 0.52],
       [0.17, 0.15],
       [0.68, 0.13],
       [0.84, 0.6 ],
       [0.38, 0.4 ],
       [0.12, 0.65],
       [0.62, 0.17],
       [0.79, 0.97],
       [0.82, 0.04],
       [0.91, 0.53],
       [0.35, 0.85],
       [0.57, 0.69],
       [0.52, 0.22],
       [0.31, 0.15],
       [0.6 , 0.02],
       [0.99, 0.91],
       [0.48, 0.76],
       [0.3 , 0.19],
       [0.58, 0.62],
       [0.65, 0.17],
       [0.6 , 0.69],
       [0.95, 0.76],
       [0.47, 0.23],
       [0.15,

In [9]:
y

array([ 511.14,  717.1 ,  607.91,  270.4 ,  289.88,  830.85, 1038.09,
        455.19,  640.17,  511.06,  177.03, 1242.52,  891.37, 1339.72,
        169.88,  276.05,  517.43,  522.25,  932.21,  851.25,  640.11,
        308.68, 1046.05,  332.4 ,  171.85,  109.55,  361.97,  872.21,
        303.7 ,  256.38,  341.2 , 1194.63,  408.6 ,  895.54,  518.25,
        638.75,  301.9 ,  163.38,  240.77, 1449.05,  609.  ,  174.59,
        593.45,  355.96,  671.46, 1193.7 ,  278.88,  411.4 ,   42.08,
        166.19,   58.62,  642.45,  368.14,  702.78,  615.74,  143.79,
        109.  ,  328.28,  205.16, 1360.49,  905.83,  487.33,  202.76,
        202.01,  148.87,  745.3 ,  503.04, 1563.82,  165.21,  438.4 ,
         98.47,  819.63,  174.44,  483.13,  534.24,  572.31,  957.61,
        518.29, 1143.49, 1211.31,  784.74,  283.7 ,  684.38,  719.46,
        292.23,  775.68,  130.77,  801.6 ,  323.55,  726.9 ,  661.12,
        771.11, 1016.14,  237.69,  325.89,  636.22,  272.12,  696.65,
        434.53,  593

In [11]:
#Diving the data in Training and testing splits
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [13]:
y_train

array([ 355.96,  202.76,  270.4 ,  819.63, 1193.7 ,   42.08, 1038.09,
        593.86,  684.38,  957.61,  905.83,  784.74,  661.12,  165.21,
        642.45,  872.21,  932.21,  109.  ,  202.01,  534.24,  717.1 ,
        487.33,  593.45,  174.59,  289.88,  276.05,  522.25,  609.  ,
        240.77,  830.85,  771.11, 1360.49,  511.14,  518.25,  303.7 ,
         58.62, 1242.52,  638.75,  332.4 ,  368.14,  177.03, 1194.63,
        503.04,  328.28, 1211.31,  775.68,  408.6 ,  292.23,  169.88,
        726.9 ,  851.25,  256.38,  166.19,  696.65,  434.53,  438.4 ,
        640.11,  325.89,  174.44,  518.29,  109.55,  163.38,  283.7 ,
        278.88, 1449.05,  745.3 ,  205.16,  891.37,  323.55,   98.47,
        801.6 ,  301.9 ,  308.68,  719.46,  511.06,  272.12, 1563.82,
        148.87,  411.4 ,  671.46])

### Model Building

In [15]:
#Creating the model
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
model1 = lr.fit(X_train, y_train)

In [47]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree=3)  #Here the degree is passed as 3
X_poly = poly.fit_transform(X_train)
model2 = lr.fit(X_poly, y_train) 

In [48]:
y_pred = model2.predict(poly.fit_transform(X_test))

In [49]:
model2.score(X_poly, y_train)
#The model has succesfully predicted the accuracy of 99% on training data 

0.9998421736843853

In [50]:
model2.score(poly.fit_transform(X_test), y_test)
#The model has the accuracy of 99 Percentage on testing data

0.999800019894562

In [51]:
df_compare = pd.DataFrame(y_test, columns=['Actual'])
df_compare['Predicted'] = y_pred

In [52]:
#Comparing Actual and predicted data
df_compare

Actual    Predicted
0    361.97   359.503603
1    130.77   131.238344
2    607.91   609.169310
3    143.79   149.984128
4    572.31   566.721016
5    237.69   237.763033
6    517.43   520.609340
7    483.13   485.307705
8    615.74   619.830899
9    636.22   632.505777
10   702.78   703.213763
11  1016.14  1024.987286
12  1143.49  1151.245583
13  1339.72  1330.850546
14   455.19   460.705800
15   341.20   340.841365
16  1046.05  1041.642470
17   171.85   170.759984
18   895.54   901.578390
19   640.17   636.040947

In [53]:
#Checking Errors
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_pred, y_test)
mse

22.241818750636366

## Conclusion:
1. Succesfully created a Polynomial Regrression model with degree =3.
2. Accuracy is about 99% on both training and testing splits along with less mean squared error